version: '3'
services:
  azure-vote-back2:
    image: redis
    container_name: azure-vote-back2
    ports:
        - "6379:6379"

  azure-vote-front2:
    build: ./azure-vote
    image: azure-vote-front2
    container_name: azure-vote-front2
    environment:
      REDIS: azure-vote-back2
    ports:
        - "8080:80"
